# Dataset 1



## Data input and basic processing

importing numpy and pandas also sklearn for errors

In [334]:
import numpy as np 
import pandas as pd
from sklearn.metrics import mean_squared_error
from sklearn.metrics import mean_absolute_error

Importing and looking at the data

In [335]:
main_df = pd.read_csv("housing.data",header = None)
main_df.head()

0     1     2   3      4      5     6       7   8      9     10  \
0  0.00632  18.0  2.31   0  0.538  6.575  65.2  4.0900   1  296.0  15.3   
1  0.02731   0.0  7.07   0  0.469  6.421  78.9  4.9671   2  242.0  17.8   
2  0.02729   0.0  7.07   0  0.469  7.185  61.1  4.9671   2  242.0  17.8   
3  0.03237   0.0  2.18   0  0.458  6.998  45.8  6.0622   3  222.0  18.7   
4  0.06905   0.0  2.18   0  0.458  7.147  54.2  6.0622   3  222.0  18.7   

       11    12    13  
0  396.90  4.98  24.0  
1  396.90  9.14  21.6  
2  392.83  4.03  34.7  
3  394.63  2.94  33.4  
4  396.90  5.33  36.2

In [336]:
main_df.describe()

0           1           2           3           4           5   \
count  506.000000  506.000000  506.000000  506.000000  506.000000  506.000000   
mean     3.613524   11.363636   11.136779    0.069170    0.554695    6.284634   
std      8.601545   23.322453    6.860353    0.253994    0.115878    0.702617   
min      0.006320    0.000000    0.460000    0.000000    0.385000    3.561000   
25%      0.082045    0.000000    5.190000    0.000000    0.449000    5.885500   
50%      0.256510    0.000000    9.690000    0.000000    0.538000    6.208500   
75%      3.677083   12.500000   18.100000    0.000000    0.624000    6.623500   
max     88.976200  100.000000   27.740000    1.000000    0.871000    8.780000   

               6           7           8           9           10          11  \
count  506.000000  506.000000  506.000000  506.000000  506.000000  506.000000   
mean    68.574901    3.795043    9.549407  408.237154   18.455534  356.674032   
std     28.148861    2.105710    8.707259  168.537116    2.164946   91.294864   
min      2.900000    1.129600    1.000000  187.000000   12.600000    0.320000   
25%     45.025000    2.100175    4.000000  279.000000   17.400000  375.377500   
50%     77.500000    3.207450    5.000000  330.000000   19.050000  391.440000   
75%     94.075000    5.188425   24.000000  666.000000   20.200000  396.225000   
max    100.000000   12.126500   24.000000  711.000000   22.000000  396.900000   

               12          13  
count  506.000000  506.000000  
mean    12.653063   22.532806  
std      7.141062    9.197104  
min      1.730000    5.000000  
25%      6.950000   17.025000  
50%     11.360000   21.200000  
75%     16.955000   25.000000  
max     37.970000   50.000000

In [337]:
names_mapper = {
    0:"CRIM",
    1:"ZN",
    2:"INDUS", 
    3:"CHAS", 
    4:"NOX", 
    5:"RM", 
    6:"AGE", 
    7:"DIS", 
    8:"RAD", 
    9:"TAX", 
    10:"PTRATIO",
    11:"B",
    12:"LSTAT",
    13:"MEDV"
}

main_df.rename(axis="columns", mapper=names_mapper, inplace=True)
main_df.head()

CRIM    ZN  INDUS  CHAS    NOX     RM   AGE     DIS  RAD    TAX  \
0  0.00632  18.0   2.31     0  0.538  6.575  65.2  4.0900    1  296.0   
1  0.02731   0.0   7.07     0  0.469  6.421  78.9  4.9671    2  242.0   
2  0.02729   0.0   7.07     0  0.469  7.185  61.1  4.9671    2  242.0   
3  0.03237   0.0   2.18     0  0.458  6.998  45.8  6.0622    3  222.0   
4  0.06905   0.0   2.18     0  0.458  7.147  54.2  6.0622    3  222.0   

   PTRATIO       B  LSTAT  MEDV  
0     15.3  396.90   4.98  24.0  
1     17.8  396.90   9.14  21.6  
2     17.8  392.83   4.03  34.7  
3     18.7  394.63   2.94  33.4  
4     18.7  396.90   5.33  36.2

In [338]:
main_df.describe()

CRIM          ZN       INDUS        CHAS         NOX          RM  \
count  506.000000  506.000000  506.000000  506.000000  506.000000  506.000000   
mean     3.613524   11.363636   11.136779    0.069170    0.554695    6.284634   
std      8.601545   23.322453    6.860353    0.253994    0.115878    0.702617   
min      0.006320    0.000000    0.460000    0.000000    0.385000    3.561000   
25%      0.082045    0.000000    5.190000    0.000000    0.449000    5.885500   
50%      0.256510    0.000000    9.690000    0.000000    0.538000    6.208500   
75%      3.677083   12.500000   18.100000    0.000000    0.624000    6.623500   
max     88.976200  100.000000   27.740000    1.000000    0.871000    8.780000   

              AGE         DIS         RAD         TAX     PTRATIO           B  \
count  506.000000  506.000000  506.000000  506.000000  506.000000  506.000000   
mean    68.574901    3.795043    9.549407  408.237154   18.455534  356.674032   
std     28.148861    2.105710    8.707259  168.537116    2.164946   91.294864   
min      2.900000    1.129600    1.000000  187.000000   12.600000    0.320000   
25%     45.025000    2.100175    4.000000  279.000000   17.400000  375.377500   
50%     77.500000    3.207450    5.000000  330.000000   19.050000  391.440000   
75%     94.075000    5.188425   24.000000  666.000000   20.200000  396.225000   
max    100.000000   12.126500   24.000000  711.000000   22.000000  396.900000   

            LSTAT        MEDV  
count  506.000000  506.000000  
mean    12.653063   22.532806  
std      7.141062    9.197104  
min      1.730000    5.000000  
25%      6.950000   17.025000  
50%     11.360000   21.200000  
75%     16.955000   25.000000  
max     37.970000   50.000000

## Preprocessing

It is given that none of the data is missing but still we are doing the preprocessing

### Checking Null Values

In [339]:
main_df.isna().sum()

CRIM       0
ZN         0
INDUS      0
CHAS       0
NOX        0
RM         0
AGE        0
DIS        0
RAD        0
TAX        0
PTRATIO    0
B          0
LSTAT      0
MEDV       0
dtype: int64

In [340]:
(main_df == "?").sum()

CRIM       0
ZN         0
INDUS      0
CHAS       0
NOX        0
RM         0
AGE        0
DIS        0
RAD        0
TAX        0
PTRATIO    0
B          0
LSTAT      0
MEDV       0
dtype: int64

### Checking Duplicates

In [341]:
main_df.duplicated().sum()

0

### One-Hot Encoding:

In [342]:
#saving non one-hot coded data first
main_df_copy = main_df.copy()

column_names_to_one_hot = ["CHAS"]
main_df = pd.get_dummies(main_df, columns=column_names_to_one_hot)

In [343]:
main_df.head()

CRIM    ZN  INDUS    NOX     RM   AGE     DIS  RAD    TAX  PTRATIO  \
0  0.00632  18.0   2.31  0.538  6.575  65.2  4.0900    1  296.0     15.3   
1  0.02731   0.0   7.07  0.469  6.421  78.9  4.9671    2  242.0     17.8   
2  0.02729   0.0   7.07  0.469  7.185  61.1  4.9671    2  242.0     17.8   
3  0.03237   0.0   2.18  0.458  6.998  45.8  6.0622    3  222.0     18.7   
4  0.06905   0.0   2.18  0.458  7.147  54.2  6.0622    3  222.0     18.7   

        B  LSTAT  MEDV  CHAS_0  CHAS_1  
0  396.90   4.98  24.0       1       0  
1  396.90   9.14  21.6       1       0  
2  392.83   4.03  34.7       1       0  
3  394.63   2.94  33.4       1       0  
4  396.90   5.33  36.2       1       0

In [344]:
main_df.dtypes

CRIM       float64
ZN         float64
INDUS      float64
NOX        float64
RM         float64
AGE        float64
DIS        float64
RAD          int64
TAX        float64
PTRATIO    float64
B          float64
LSTAT      float64
MEDV       float64
CHAS_0       uint8
CHAS_1       uint8
dtype: object

Pre-Processing -- Done

- No NaN or Null values or ? found
- No duplicates found

## Train Test Split

As the size of data is not very large we are using 60%(training) to 40%(testing) split as discussed in Tutorial session.

In [345]:
# Separating the expected output from features

y = main_df["MEDV"].to_numpy()
main_df.drop(axis="columns", labels="MEDV", inplace=True)
X = main_df.to_numpy()
# print(X)
# print(y)

In [346]:
def train_test_split(X,y,training_size):

    np.random.seed(0)
    random_order = np.random.permutation(X.shape[0])

    # Below given is using random_order to randomly order the rows exactly in same order in both X and y
    X = X[random_order]
    y = y[random_order]

    division = int(training_size*X.shape[0])

    train_x = X[0:division,:]
    train_y = y[0:division]
    test_x = X[division:]
    test_y = y[division:]
    
    return (train_x,train_y,test_x,test_y)

In [347]:
train_x,train_y,test_x,test_y = train_test_split(X,y,0.6)

## Linear Regression

### Gradient Descent

#### Multivariate 

In [348]:
#function to normalise data before finding gradient
def normalize(train_x,test_x):
    
    mean = []
    std = []

    for i in range(train_x.shape[1]):
        mean.append(train_x[:,i].mean())
        std.append(train_x[:,i].std())

    for i in range(train_x.shape[1]):
        for j in range(train_x.shape[0]):
            train_x[j,i] = (train_x[j,i]-mean[i])
            train_x[j,i] = (train_x[j,i]/std[i])

    for i in range(test_x.shape[1]):
        for j in range(test_x.shape[0]):
            test_x[j,i] = (test_x[j,i]-mean[i])
            test_x[j,i] = (test_x[j,i]/std[i])

    return (train_x,test_x)


##### Checking All Combinations of Features and trying to come up with best possible model.

In [349]:
from itertools import combinations
from matplotlib import pyplot as mpl

def gradient_descent(X,y,meu,iter):
    no_of_rows = X.shape[0]
    no_of_columns = X.shape[1]
    W = np.ones((no_of_columns,)).reshape(-1,1) # making a column 2d vector from 1d vector
    y = y.reshape(-1,1) # making a column 2d vector from 1d vector

    temp_cost = (1/no_of_rows)*( (((X@W)-y).T) @ ((X@W)-y) )[0,0]
    old_cost = 9223372036854775807 # infinity
    cost = []
    cost.append(temp_cost)

    i=0
    while(i<=iter and old_cost-temp_cost >= 0.000001):
        i+=1
        
        W = W - meu*((1/no_of_rows)*((X.T) @ (X@W-y)))
        old_cost = temp_cost
        
        temp_cost = (1/no_of_rows)*( (((X@W)-y).T) @ ((X@W)-y) )[0,0]
        cost.append(temp_cost)
        
        if temp_cost > old_cost:
            return (W,-1)
    
    return (W,temp_cost)


def gradient_for_combination(normalised_train_x,y,comb,meu,iter):
    
    columns = list(comb)
        
    new_X_normalised = normalised_train_x[:,columns]

    ones_columns = np.ones((new_X_normalised.shape[0],)).reshape(-1,1)
    full_new_X = np.concatenate((ones_columns,new_X_normalised),axis=1)
    tup=gradient_descent(full_new_X,y,meu,iter)
    # print(tup)
    return tup

def best_combination(normalised_train_x,y):
    
    possibilities = []

    no_of_columns = normalised_train_x.shape[1]
    
    for i in range(no_of_columns):
        # they were taking a lot of time for the computation
        if(i==4 or i== 5 or i== 6):
            continue
        comb = combinations(range(no_of_columns), i+1)        
        for i in list(comb):
            if( 12 in i):
                if(13 not in i):
                    continue
            if( 13 in comb):
                if(12 not in comb):
                    continue
            possibilities.append(i)
    
    best_comb = possibilities[0]
    best_accuracy = gradient_for_combination(normalised_train_x,y,best_comb,0.001,6000)

    for i in possibilities:

        if(len(i) <= 2):
            temp = gradient_for_combination(normalised_train_x,y,i,0.001,6000)
        else:
            temp = gradient_for_combination(normalised_train_x,y,i,0.05,1000)

        if(temp[1] == -1):
            continue
        if temp[1]<best_accuracy[1]:
            best_accuracy = temp
            best_comb = i
    
    return (best_accuracy,best_comb)
    


In [350]:
train_x_copy = np.ndarray.copy( train_x)
test_x_copy = np.ndarray.copy( test_x)
normalised_train_x,normalised_test_x = normalize(train_x_copy,test_x_copy)
# print(gradient_for_combination(normalised_train_x,train_y,[0,1,2,3,4,6,7,8,9,10,11,12,13]))
tuple_returned = best_combination(normalised_train_x,train_y)

In [351]:
W = tuple_returned[0][0]
columns = tuple_returned[1]
columns = list(columns)

#### Error Calculations

In [352]:
# mean absolute relative error
mean_absolute_relative_error = lambda y, yhat, epsilon: (100/y.size)*np.sum((np.abs(y-yhat)/(np.abs(y) + epsilon)))

In [353]:
def error_calc(train_x,test_x,train_y,test_y,columns):
    
    train_x_copy = np.ndarray.copy( train_x)
    test_x_copy = np.ndarray.copy( test_x)
    normalised_train_x,normalised_test_x = normalize(train_x_copy,test_x_copy)

    normalised_train_x = normalised_train_x[:,columns]
    normalised_test_x = normalised_test_x[:,columns]

    first_column = np.ones((normalised_train_x.shape[0],)).reshape(-1,1)
    normalised_train_x = np.concatenate((first_column,normalised_train_x),axis=1)
    
    first_column = np.ones((normalised_test_x.shape[0],)).reshape(-1,1)
    normalised_test_x = np.concatenate((first_column,normalised_test_x),axis=1)
    
    train_ypred = normalised_train_x @ W
    test_ypred = normalised_test_x @ W
    
    print("Training VS Testing\n")
    print("Mean Squared Error - " + str(mean_squared_error(train_y, train_ypred)) + " " + str(mean_squared_error(test_y, test_ypred)))
    print("Mean Absolute Error - " + str(mean_absolute_error(train_y, train_ypred)) + " " + str(mean_absolute_error(test_y, test_ypred)))
    train_ypred = np.reshape(train_ypred,-1)
    test_ypred = np.reshape(test_ypred,-1)
    print("Mean Absolute Relative Error - " + str(mean_absolute_relative_error(train_y, train_ypred,0.01)) + " " + str(mean_absolute_relative_error(test_y, test_ypred,0.01)))

##### Error Calculation in Training Data vs Testing Data

In [354]:
error_calc(train_x,test_x,train_y,test_y,columns)

Training VS Testing

Mean Squared Error - 22.03558259649766 22.58080104224621
Mean Absolute Error - 3.238419581720472 3.309702517731528
Mean Absolute Relative Error - 16.006038542706797 17.372705914776727


##### Special case searching for finding best univariate feature

In [355]:
for i in range(14):
    test = [i]
    print(gradient_for_combination(normalised_train_x,train_y,test,0.001,15000))

(array([[22.13489215],
       [-3.40552182]]), 64.96842430896187)
(array([[22.13451693],
       [ 2.86553313]]), 68.37453938566428)
(array([[22.1350448 ],
       [-4.06042134]]), 60.06779602631285)
(array([[22.13497951],
       [-3.78726422]]), 62.21630550013399)
(array([[22.1350013 ],
       [ 5.88589724]]), 41.89403843921352)
(array([[22.13489215],
       [-3.30503605]]), 65.64434367312079)
(array([[22.13447236],
       [ 2.31576313]]), 71.22788962615628)
(array([[22.13489215],
       [-3.31423448]]), 65.58331174267333)
(array([[22.1350448],
       [-4.0173942]]), 60.41616416817323)
(array([[22.1351099 ],
       [-4.29194782]]), 58.12968792216385)
(array([[22.1345614 ],
       [ 3.26272322]]), 65.93619725237468)
(array([[22.13566597],
       [-6.3091377 ]]), 36.69973451507083)
(array([[22.13458361],
       [-1.54493008]]), 74.20200950508479)
(array([[22.13445005],
       [ 1.54702355]]), 74.20200864721127)


#### Univariate

In [356]:
tuple_returned = gradient_for_combination(normalised_train_x,train_y,[11],0.001,15000)
W = tuple_returned[0]
error_calc(train_x,test_x,train_y,test_y,[11])

Training VS Testing

Mean Squared Error - 36.69973451507083 41.73681217429911
Mean Absolute Error - 4.330540042488694 4.5660072494405854
Mean Absolute Relative Error - 20.5386774483734 20.96435989900394


### Closed Form

#### Train Test Split
We need to use label encoding instead of one-hot encoding as one-hot encoding results in linearly dependent columns. We have already done preprocessing but we need to do Train Test Split Again.

In [357]:
y = main_df_copy["MEDV"].to_numpy()
main_df_copy.drop(axis="columns", labels=["MEDV","AGE"], inplace=True) # I have cross checked it with above function
main_df_copy.head()


CRIM    ZN  INDUS  CHAS    NOX     RM     DIS  RAD    TAX  PTRATIO  \
0  0.00632  18.0   2.31     0  0.538  6.575  4.0900    1  296.0     15.3   
1  0.02731   0.0   7.07     0  0.469  6.421  4.9671    2  242.0     17.8   
2  0.02729   0.0   7.07     0  0.469  7.185  4.9671    2  242.0     17.8   
3  0.03237   0.0   2.18     0  0.458  6.998  6.0622    3  222.0     18.7   
4  0.06905   0.0   2.18     0  0.458  7.147  6.0622    3  222.0     18.7   

        B  LSTAT  
0  396.90   4.98  
1  396.90   9.14  
2  392.83   4.03  
3  394.63   2.94  
4  396.90   5.33

In [358]:
X = main_df_copy.to_numpy()
train_x,train_y,test_x,test_y = train_test_split(X,y,0.6)

#### Multivariate 

##### Calculating W

In [359]:
def closed_form(X,y):
    temp = X.T @ X
    W = (np.linalg.inv(temp) @ X.T) @ y
    return W

In [360]:
train_x_copy = np.ndarray.copy( train_x)
test_x_copy = np.ndarray.copy( test_x)
normalised_train_x,normalised_test_x = normalize(train_x_copy,test_x_copy)

first_column = np.ones((normalised_train_x.shape[0],)).reshape(-1,1)
normalised_train_x_temp = np.concatenate((first_column,normalised_train_x),axis=1)
    
W = closed_form(normalised_train_x_temp,train_y)
columns = [0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11]

#### Error Calculations

##### Error Calculation in Training Data vs Testing Data

In [361]:
error_calc(train_x,test_x,train_y,test_y,columns)


Training VS Testing

Mean Squared Error - 22.033326145902194 22.610248378908178
Mean Absolute Error - 3.2410948545018243 3.3147537521930097
Mean Absolute Relative Error - 16.026690340512914 17.390370196549863


#### Univariate

In [362]:
train_x_copy = np.ndarray.copy( train_x)
test_x_copy = np.ndarray.copy( test_x)
normalised_train_x,normalised_test_x = normalize(train_x_copy,test_x_copy)

normalised_train_x = normalised_train_x[:,[11]]
normalised_test_x = normalised_test_x[:,[11]]

first_column = np.ones((normalised_train_x.shape[0],)).reshape(-1,1)
normalised_train_x_temp = np.concatenate((first_column,normalised_train_x),axis=1)
    
W = closed_form(normalised_train_x_temp,train_y)
columns = [11]

error_calc(train_x,test_x,train_y,test_y,[11])

Training VS Testing

Mean Squared Error - 36.69923607550484 41.695856854656114
Mean Absolute Error - 4.335996575406678 4.57005932209336
Mean Absolute Relative Error - 20.58155949020036 21.00356132617038


### Newton's Method

#### Multivariate 